client_id = "ffa122a24ec5318d7327a119ec0ddf9b"
name = "Smartbill Transfer Importer"
application_url = "https://shopify-smartbill.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/orders-create"
  topics = [ "orders/create" ]

[access_scopes]
scopes = "read_locations,write_locations,read_products,write_products,read_inventory,write_inventory,write_inventory_transfers,read_inventory_transfers,read_orders"
[auth]
redirect_urls = [ "https://shopify-smartbill.onrender.com/auth/callback" ]